'use client';

import { useEffect, useMemo, useState } from 'react';

import { ResultView } from '@/components/ResultView';
import { UnexpectedCard } from '@/app/analyze/RefusalCard';
import { VerdictBadge } from '@/components/VerdictBadge';
import type { Envelope } from '@/lib/result';
import { laneVerdicts, type LaneVerdict } from '@/lib/verdict';
import { verdictSentence } from '@/lib/verdict-sentence';

/**
 * Step 3: one verdict card per lane, and the full result surface for the lane you pick.
 *
 * The verdicts come from `lib/verdict.ts`, the pinned mirror of `api/display.py::lane_verdicts`,
 * because the API does not serve a verdict and this result was never stored. The sentence under
 * each badge is `verdictSentence`, the same function `/result/[id]` uses, so a lane analysed here
 * and the same lane shown as a gallery card read identically.
 *
 * The detail surface is `ResultView` -- the component, not a copy of it. The picture is the
 * `display.png_base64` the response carried, as a `data:` URL under the media type the response
 * declared; the download is a blob of the result document, because this document exists nowhere
 * else yet.
 */

function dataUrl(mediaType: string, base64: string): string {
  return `data:${mediaType};base64,${base64}`;
}

export function ResultStep({
  envelope,
  filename,
}: {
  envelope: Envelope;
  filename: string;
}): React.ReactElement {
  const { result, display } = envelope;
  // `lib/verdict.ts` refuses documents `api/display.py` answers for; every such shape is
  // recorded in `test/fixtures/verdict/divergences.json`, which is generated by observing the
  // Python rather than counted by hand here. This call happens during render, past every card
  // below, and the API is what supplies the document. Uncaught,
  // Next replaces the whole page with its generic client-error screen and the `VerdictError`'s
  // actionable text is discarded, which is the exact failure `lib/api.ts` says it exists to
  // prevent. `requireEnvelope` closed the shape hole; this closes the verdict one.
  let verdicts: LaneVerdict[];
  let verdictFailure: Error | null = null;
  try {
    verdicts = laneVerdicts({ ...result } as Record<string, unknown>);
  } catch (error) {
    verdicts = [];
    verdictFailure = error instanceof Error ? error : new Error(String(error));
  }
  const [chosenLaneId, setChosenLaneId] = useState<string | null>(null);
  const activeLaneId = chosenLaneId ?? verdicts[0]?.lane_id ?? null;

  // The document is not on any server this page can link to, so the download is assembled here.
  // Revoked on unmount and whenever the document changes, so a second analysis does not leak the
  // first one's blob.
  const [downloadHref, setDownloadHref] = useState<string | null>(null);
  useEffect(() => {
    const url = URL.createObjectURL(
      new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' }),
    );
    setDownloadHref(url);
    return () => URL.revokeObjectURL(url);
  }, [result]);

  const imageSrc = useMemo(
    () => dataUrl(display.media_type, display.png_base64),
    [display.media_type, display.png_base64],
  );

  if (verdictFailure !== null) {
    return (
      <div>
        <h2 className="text-base font-semibold">3 · Result</h2>
        <p className="mt-2 text-sm text-[var(--color-ink-muted)]">
          The API answered, and the document it returned cannot be read back by the verdict
          derivation. No verdict is shown, because there is none to show.
        </p>
        <div className="mt-4">
          <UnexpectedCard error={verdictFailure} />
        </div>
      </div>
    );
  }

  return (
    <div>
      <h2 className="text-base font-semibold">3 · Result</h2>
      <p className="tabular mt-1 text-xs text-[var(--color-ink-muted)]">
        result_id {result.result_id} · config {result.provenance.config_id} · pipeline{' '}
        {result.provenance.software_version} · {result.source.width_px}×{result.source.height_px}{' '}
        px · {result.source.bit_depth}-bit {result.source.image_format}
      </p>

      <ul className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {verdicts.map((verdict) => {
          const active = verdict.lane_id === activeLaneId;
          return (
            <li key={verdict.lane_id}>
              <button
                type="button"
                aria-pressed={active}
                onClick={() => setChosenLaneId(verdict.lane_id)}
                className="w-full border p-3 text-left"
                style={{
                  borderColor: active
                    ? 'var(--color-accent)'
                    : 'var(--color-hairline)',
                  backgroundColor: active
                    ? 'var(--color-surface-sunken)'
                    : 'var(--color-surface-raised)',
                }}
              >
                <span className="flex items-center gap-2">
                  <VerdictBadge verdict={verdict.verdict} size="card" />
                  <span className="tabular text-sm font-medium">{verdict.lane_id}</span>
                </span>
                <span className="mt-2 block text-xs">{verdictSentence(verdict)}</span>
                <span className="tabular mt-1 block text-xs text-[var(--color-ink-muted)]">
                  {verdict.band_count} bands · {verdict.usable_ratio_count}/
                  {verdict.ratio_count} ratios usable
                </span>
              </button>
            </li>
          );
        })}
      </ul>

      {activeLaneId !== null && (
        <div className="mt-8">
          <ResultView
            document={result}
            display={display}
            imageSrc={imageSrc}
            laneId={activeLaneId}
            download={downloadHref === null ? null : { href: downloadHref, filename }}
          />
        </div>
      )}
    </div>
  );
}
