import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { BAND_QC_FLAGS, VerdictError, asDict, laneVerdicts } from '@/lib/verdict';

/**
 * The anti-divergence test.
 *
 * `web/lib/verdict.ts` is a second implementation of a ruled mapping
 * (`docs/PRE_REGISTRATION_2026-08-25_verdict_mapping.md`, Ruling 1). The fixtures under
 * `test/fixtures/verdict/` are generated by `tools/gallery/verdict_fixtures.py` by calling the
 * **Python** `api.display.lane_verdicts`, so what is asserted below is that the TypeScript
 * reproduces the Python -- not that it satisfies a second statement of the rule written here.
 *
 * `tests/test_gallery_verdict_fixtures.py` keeps the fixtures in step with `api/display.py`.
 * Between the two, a change to the mapping that reaches only one implementation fails a build.
 */

const FIXTURE_DIR = join(__dirname, 'fixtures', 'verdict');
const ERROR_DIR = join(FIXTURE_DIR, 'errors');

/**
 * The floors below exist because the failure this whole mechanism is built against is a green
 * test over an empty fixture set: a glob that matched nothing would pass every assertion in this
 * file. They are **floors, never censuses**, and no prose anywhere may quote them as the size of
 * the fixture set. That prohibition is written here because the identical sentence on
 * `MINIMUM_DIVERGENCE_CASES` -- "raised deliberately when the generator gains a case" -- turned
 * out to be false: three cases were added, the floor was not raised, and its stale value was then
 * copied into two files as though it were a count. The size of each set is what the generator
 * emits; the guarantee here is only that neither has been hollowed out. Gallery fixtures are
 * counted separately and are not floored -- the gallery's size is the human's selection.
 */
const MINIMUM_SYNTHETIC_FIXTURES = 18;
const MINIMUM_ERROR_FIXTURES = 9;

/**
 * The cases §5 of the pre-registration requires to be covered. Named rather than counted, so a
 * case dropped from the generator fails here by name instead of shifting a number.
 */
const REQUIRED_FIXTURE_PREFIXES = [
  'class_pass',
  'class_flagged',
  'class_blocked_all_ratios_excluded',
  'class_blocked_no_ratio_emitted',
  'e1_',
  'e2_',
  'e3_',
  'e4_',
  'e5_',
  'e7_',
  'e8_',
  'mutation_walk_1_',
  'mutation_walk_2_',
  'mutation_walk_3_',
  'ordering_flags_follow_the_vocabulary',
  'ordering_unknown_flag_sorts_last',
  'ordering_verdicts_follow_the_documents_lane_order',
  'optional_ratio_flag_keys_are_absent',
];

/**
 * The generator's vocabulary fixture, which is not a case: it carries no document and no
 * expected verdict, so it is excluded from the case sweeps and asserted on its own below.
 */
const VOCABULARY_FILE = 'vocabulary.json';

/**
 * The generated record of what the Python does with a schema-invalid document. Like
 * `vocabulary.json` it is not a case fixture -- it carries no single document and no expected
 * verdict -- so it is excluded from the case sweeps and asserted on its own.
 */
const DIVERGENCE_FILE = 'divergences.json';

interface VerdictFixture {
  name: string;
  why: string;
  document: Record<string, unknown>;
  expected: Record<string, unknown>[];
}

interface ErrorFixture {
  name: string;
  why: string;
  document: Record<string, unknown>;
  expected_error: true;
}

function load<T>(directory: string): { file: string; fixture: T }[] {
  return readdirSync(directory)
    .filter(
      (name) =>
        name.endsWith('.json') && name !== VOCABULARY_FILE && name !== DIVERGENCE_FILE,
    )
    .sort()
    .map((file) => ({
      file,
      fixture: JSON.parse(readFileSync(join(directory, file), 'utf-8')) as T,
    }));
}

const verdictFixtures = load<VerdictFixture>(FIXTURE_DIR);
const errorFixtures = load<ErrorFixture>(ERROR_DIR);

describe('the flag vocabulary', () => {
  /**
   * The vocabulary is an *input* to the mapping, so no case fixture can pin it.
   *
   * `_ordered_flags` reports a lane's flags in `BAND_QC_FLAGS` order and sorts anything outside
   * the vocabulary last. `lib/verdict.ts` retypes that tuple instead of importing it, so a flag
   * added to `pipeline/qc.py` would take a vocabulary position in the Python and sort as an
   * unknown in the TypeScript -- a real ordering difference in production that no document-plus-
   * verdict fixture could ever contain, because no fixture would carry the new flag. This
   * asserts the constant itself against the tuple the Python wrote out.
   */
  it('is exactly the tuple api/display.py orders flags by, in its order', () => {
    const fixture = JSON.parse(
      readFileSync(join(FIXTURE_DIR, VOCABULARY_FILE), 'utf-8'),
    ) as { band_qc_flags: string[] };
    expect(fixture.band_qc_flags.length).toBeGreaterThan(0);
    expect([...BAND_QC_FLAGS]).toEqual(fixture.band_qc_flags);
  });
});

describe('the fixture set itself', () => {
  it('is not empty', () => {
    expect(verdictFixtures.length).toBeGreaterThan(0);
    expect(errorFixtures.length).toBeGreaterThan(0);
  });

  it('carries at least the synthetic cases the generator emits', () => {
    const synthetic = verdictFixtures.filter(({ file }) => !file.startsWith('gallery__'));
    expect(synthetic.length).toBeGreaterThanOrEqual(MINIMUM_SYNTHETIC_FIXTURES);
    expect(errorFixtures.length).toBeGreaterThanOrEqual(MINIMUM_ERROR_FIXTURES);
  });

  it('includes a fixture for every case the pre-registration requires', () => {
    const names = verdictFixtures.map(({ fixture }) => fixture.name);
    const errorNames = errorFixtures.map(({ fixture }) => fixture.name);
    for (const prefix of REQUIRED_FIXTURE_PREFIXES) {
      expect(names.some((name) => name.startsWith(prefix))).toBe(true);
    }
    // E6 is ruled *raise*, so its fixtures are refusals rather than verdicts.
    expect(errorNames.some((name) => name.startsWith('e6_'))).toBe(true);
  });

  it('includes every card in the committed gallery', () => {
    const gallery = verdictFixtures.filter(({ file }) => file.startsWith('gallery__'));
    expect(gallery.length).toBeGreaterThan(0);
  });
});

describe('laneVerdicts reproduces api/display.py', () => {
  it.each(verdictFixtures.map(({ file, fixture }) => [file, fixture] as const))(
    '%s',
    (_file, fixture) => {
      const produced = laneVerdicts(fixture.document).map(asDict);
      // A deep equality over the whole list: the verdict, the blocked reason's presence or
      // absence, the counts, and the flag list *in order*. Comparing sets of flags would let the
      // ordering rule -- vocabulary order, unknowns last -- drift unnoticed.
      expect(produced).toEqual(fixture.expected);
      expect(produced.map((verdict) => verdict['qc_flags'])).toEqual(
        fixture.expected.map((verdict) => verdict['qc_flags']),
      );
    },
  );

  it('returns one verdict per lane, in the document order', () => {
    for (const { fixture } of verdictFixtures) {
      const lanes = fixture.document['lanes'] as { lane_id: string }[];
      expect(laneVerdicts(fixture.document).map((verdict) => verdict.lane_id)).toEqual(
        lanes.map((lane) => lane.lane_id),
      );
    }
  });

  it('does not mutate the document it reads', () => {
    for (const { fixture } of verdictFixtures) {
      const before = JSON.stringify(fixture.document);
      laneVerdicts(fixture.document);
      expect(JSON.stringify(fixture.document)).toBe(before);
    }
  });
});

describe('laneVerdicts refuses what api/display.py refuses', () => {
  it.each(errorFixtures.map(({ file, fixture }) => [file, fixture] as const))(
    '%s',
    (_file, fixture) => {
      expect(fixture.expected_error).toBe(true);
      expect(() => laneVerdicts(fixture.document)).toThrow(VerdictError);
    },
  );
});

describe('the divergences from the Python', () => {
  /**
   * Asserted against a table of what the Python **actually does**, not against a description.
   *
   * `tools/gallery/verdict_fixtures.py` runs `api.display.lane_verdicts` over each
   * schema-invalid document and records the outcome it observed: returns with these verdicts, or
   * raises this class. This file then requires the TypeScript to refuse every one of them.
   *
   * The table is generated because the hand-written version of this claim in NOTES.md was wrong
   * on three successive reviews -- and one of its errors is visible in the fixture itself:
   * `lanes: {}` *refuses* when a band names the missing lane and *returns a lane-less result*
   * when nothing does, which is not a distinction prose was ever going to keep straight.
   *
   * The structural difference the table measures: `api/display.py` checks that a key is present
   * and then iterates whatever it finds, while this module checks the types
   * `schema/result.schema.json` declares. Where the Python "returns", it produced a confident
   * verdict from a document the schema forbids.
   */
  interface DivergenceCase {
    name: string;
    why: string;
    document: Record<string, unknown>;
    python:
      | { outcome: 'returns'; refuses: false; verdicts: Record<string, unknown>[] }
      | { outcome: 'raises'; refuses: boolean; error_type: string };
  }

  const table = JSON.parse(
    readFileSync(join(FIXTURE_DIR, DIVERGENCE_FILE), 'utf-8'),
  ) as { cases: DivergenceCase[] };

  it('covers every field the derivation reads', () => {
    expect(table.cases.length).toBeGreaterThanOrEqual(20);
    // The floor exists for the same reason the fixture floors above do: a table that matched
    // nothing would pass every assertion below.
    const unrefused = table.cases.filter(({ python }) => !python.refuses);
    expect(unrefused.length).toBeGreaterThan(0);
  });

  it.each(table.cases.map((entry) => [entry.name, entry] as const))(
    'refuses %s',
    (_name, entry) => {
      expect(() => laneVerdicts(entry.document)).toThrow(VerdictError);
    },
  );

  it('records, for each case the Python does not refuse, what it returned instead', () => {
    // Not an assertion about the TypeScript: this is the divergence itself, made legible. A
    // case whose recorded outcome is `returns` is one where the API would answer with a verdict
    // for a document the browser refuses to read.
    for (const { name, python } of table.cases) {
      if (python.outcome === 'returns') {
        expect(Array.isArray(python.verdicts)).toBe(true);
      } else {
        expect(typeof python.error_type).toBe('string');
        expect(python.error_type.length, name).toBeGreaterThan(0);
      }
    }
  });

  it('still reads a genuine document either way round', () => {
    const base = {
      lanes: [{ lane_id: 'L0', roi_source: 'caller' }],
      bands: [{ band_id: 'L0_B0', lane_id: 'L0', qc_flags: [] }],
      image_qc_flags: [],
    };
    for (const [excluded, verdict] of [
      [false, 'pass'],
      [true, 'blocked'],
    ] as const) {
      const document = {
        ...base,
        normalization: {
          ratios: [{ lane_id: 'L0', numerator_band_id: 'L0_B0', excluded, qc_flags: [] }],
        },
      };
      expect(laneVerdicts(document)[0]?.verdict).toBe(verdict);
    }
  });
});

describe('unknown flags sort by code point, as Python sorts them', () => {
  it('orders a non-BMP flag after a high BMP one, where a naive sort would not', () => {
    // `orderedFlags` puts unknown flags after the vocabulary and sorts them with an explicit
    // code-point comparison, because JavaScript's default sort compares UTF-16 *code units* and
    // Python's `sorted` compares code points. The two disagree above the basic multilingual
    // plane, and `verdict.ts` documents that its comparator is what makes "the TypeScript sorts
    // unknown flags the way the Python does" true rather than true-in-practice -- while noting
    // the fixture set cannot demonstrate it, since every real flag is ASCII.
    //
    // This is that demonstration. U+1F600 encodes as the surrogate pair D83D DE00, so its first
    // code unit (D83D) is *below* U+FF01 -- a default sort emits it first. By code point it is
    // far above, so Python emits U+FF01 first. Asserting the Python order pins the comparator.
    const emoji = '\u{1F600}';
    const fullwidth = '！';
    const document = {
      lanes: [{ lane_id: 'L0', roi_source: 'caller' }],
      bands: [{ band_id: 'L0_B0', lane_id: 'L0', qc_flags: [emoji, fullwidth, 'saturated'] }],
      normalization: {
        ratios: [{ lane_id: 'L0', numerator_band_id: 'L0_B0', excluded: false, qc_flags: [] }],
      },
      image_qc_flags: [],
    };

    // Vocabulary first, then the unknowns in code-point order.
    expect(laneVerdicts(document)[0]?.qc_flags).toEqual(['saturated', fullwidth, emoji]);
    // The order a default sort would have produced, named so the test cannot pass by accident.
    expect([emoji, fullwidth].sort()).toEqual([emoji, fullwidth]);
  });
});
