import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { laneVerdicts, type LaneVerdict } from '@/lib/verdict';
import { verdictSentence } from '@/lib/verdict-sentence';

/**
 * The one sentence each verdict class gets, asserted character for character.
 *
 * The verdict records are not hand-built here: each one is derived by `laneVerdicts` from the
 * committed fixture for its class, which `tools/gallery/verdict_fixtures.py` generated by running
 * the **Python** derivation. So what is pinned is the sentence a real ruled record produces, and
 * a change to the mapping that altered which flags attach to a lane would change the flagged
 * sentence here rather than passing unnoticed.
 */

const FIXTURE_DIR = join(__dirname, 'fixtures', 'verdict');

function verdictFromFixture(name: string): LaneVerdict {
  const fixture = JSON.parse(readFileSync(join(FIXTURE_DIR, `${name}.json`), 'utf-8')) as {
    document: Record<string, unknown>;
  };
  const verdict = laneVerdicts(fixture.document)[0];
  if (verdict === undefined) {
    throw new Error(`fixture ${name} yielded no lane verdict`);
  }
  return verdict;
}

describe('verdictSentence', () => {
  it('names the blocked reason for a lane whose every ratio was excluded', () => {
    const verdict = verdictFromFixture('class_blocked_all_ratios_excluded');
    expect(verdict.verdict).toBe('blocked');
    expect(verdictSentence(verdict)).toBe(
      'No ratio carries a number: all_ratios_excluded.',
    );
  });

  it('names the other blocked reason for a lane that emitted no ratio at all', () => {
    const verdict = verdictFromFixture('class_blocked_no_ratio_emitted');
    expect(verdict.verdict).toBe('blocked');
    expect(verdictSentence(verdict)).toBe('No ratio carries a number: no_ratio_emitted.');
  });

  it('lists the flags, not a count, for a flagged lane', () => {
    const verdict = verdictFromFixture('class_flagged');
    expect(verdict.verdict).toBe('flagged');
    expect(verdict.qc_flags).toEqual(['saturated']);
    expect(verdictSentence(verdict)).toBe('Number reported and annotated: saturated.');
  });

  it('lists several flags in the verdict order, comma-separated', () => {
    // The generator's ordering fixture: more than one flag, and the order is the vocabulary's,
    // which is the property the sentence has to preserve rather than re-sort.
    const verdict = verdictFromFixture('ordering_flags_follow_the_vocabulary');
    expect(verdict.verdict).toBe('flagged');
    expect(verdictSentence(verdict)).toBe(
      `Number reported and annotated: ${verdict.qc_flags.join(', ')}.`,
    );
    expect(verdict.qc_flags.length).toBeGreaterThan(1);
  });

  it('says both halves of what a pass means', () => {
    const verdict = verdictFromFixture('class_pass');
    expect(verdict.verdict).toBe('pass');
    expect(verdictSentence(verdict)).toBe('No QC flags; every ratio computed.');
  });

  it('refuses to describe a blocked record with no recorded reason', () => {
    const verdict = verdictFromFixture('class_blocked_all_ratios_excluded');
    expect(() => verdictSentence({ ...verdict, blocked_reason: null })).toThrow(
      /blocked with no blocked_reason/,
    );
  });

  it('refuses to describe a flagged record carrying no flags', () => {
    const verdict = verdictFromFixture('class_flagged');
    expect(() => verdictSentence({ ...verdict, qc_flags: [] })).toThrow(
      /flagged with no QC flags/,
    );
  });
});
