import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/** `next/core-web-vitals` plus `next/typescript`, and `pnpm lint` runs with `--max-warnings 0`,
 * so a rule set to warn stops the build the same way an error does. Generated and vendored
 * directories are ignored; `test/fixtures/` is generated by `tools/gallery/verdict_fixtures.py`
 * and `public/gallery/` by `tools/gallery/build.py`, and neither is hand-edited.
 *
 * `next-env.d.ts` is ignored for the same reason: `next build` writes it, it is gitignored, it
 * says "This file should not be edited" in its own body, and the triple-slash references it emits
 * are what `@typescript-eslint/triple-slash-reference` forbids. Silencing the rule for the whole
 * project to accommodate one generated file would turn the rule off where it applies. */
const config = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'node_modules/**',
      'public/gallery/**',
      'test/fixtures/**',
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;
